# This viminfo file was generated by Vim 8.0.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~H
# Command Line History (newest to oldest):
:q!
|2,0,1505290454,,"q!"
:Q!
|2,0,1505290452,,"Q!"
:!
|2,0,1505290447,,"!"

# Search String History (newest to oldest):

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Debug Line History (newest to oldest):

# Registers:

# File marks:
'0  1  0  /home/kunal/docker-space/kubernets-terraform/k8s-terraform-ansible-sample/ansible/ansible
|4,48,1,0,1505290454,"/home/kunal/docker-space/kubernets-terraform/k8s-terraform-ansible-sample/ansible/ansible"

# Jumplist (newest first):
-'  1  0  /home/kunal/docker-space/kubernets-terraform/k8s-terraform-ansible-sample/ansible/ansible
|4,39,1,0,1505290454,"/home/kunal/docker-space/kubernets-terraform/k8s-terraform-ansible-sample/ansible/ansible"

# History of marks within files (newest to oldest):

> /home/kunal/docker-space/kubernets-terraform/k8s-terraform-ansible-sample/ansible/ansible
	*	1505290452	0
	"	1	0
